# Generated by Django 4.0.5 on 2022-07-18 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_categoria', models.CharField(max_length=20, verbose_name='titulo da categoria')),
                ('descricao_categoria', models.CharField(max_length=100, verbose_name='descrição da categoria')),
                ('imagem_categoria', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=20, verbose_name='titulo do post')),
                ('sub_titulo', models.CharField(max_length=100, verbose_name='subtitulo do post')),
                ('conteudo_post', models.CharField(max_length=10000, verbose_name='conteudo do post')),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('imagem_post', models.ImageField(upload_to='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
        ),
    ]
