# Generated by Django 4.0.5 on 2022-07-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_posts_conteudo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='conteudo_post',
            field=models.TextField(verbose_name='conteudo do post'),
        ),
    ]
