# Generated by Django 4.1.1 on 2022-09-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_posts_conteudo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='imagem_categoria',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
