# Generated by Django 4.1.1 on 2022-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_categorias_imagem_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagem_post',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
