# Generated by Django 4.1.1 on 2022-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_person_link_1_person_link_2_person_link_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='person',
            name='link_4',
        ),
        migrations.AlterField(
            model_name='person',
            name='descricao',
            field=models.TextField(max_length=400),
        ),
    ]
